apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "mockhelmrepo.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.secret.credentials.username | quote }}
  password: {{ .Values.secret.credentials.password | quote }}
type: kubernetes.io/basic-auth
